os: linux
sudo: required
dist: trusty

notifications:
  email: false

language: C

before_install:
  - sudo apt-get install -y -q mpich libmpich-dev
  - sudo apt-get install doxygen
  - sudo apt-get install cmake
  - sudo apt-get install python3
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test
  - cat bin/runtest.sh
