language: C

notifications:
email: false

env:
  global:
    - MPI=mpich

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
